var ACTION_GET_TORRENTS = 'get-torrent-list'
exports.ACTION_GET_TORRENTS = ACTION_GET_TORRENTS

var ACTION_ADD_TORRENT = 'add-torrent'
exports.ACTION_ADD_TORRENT = ACTION_ADD_TORRENT

var ACTION_REMOVE_TORRENT = 'remove-torrent'
exports.ACTION_REMOVE_TORRENT = ACTION_REMOVE_TORRENT

var ACTION_TOGGLE_TORRENT = 'toggle-torrent'
exports.ACTION_TOGGLE_TORRENT = ACTION_TOGGLE_TORRENT

var ACTION_UPDATE_TORRENT = 'update-torrent'
exports.ACTION_UPDATE_TORRENT = ACTION_UPDATE_TORRENT
